from unittest import TestCase


class Test(TestCase):
    def test_myfuncsum(self):
        self.fail()
